---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ${email_address}
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - http01:
        ingress:
          class: nginx
